''''''''''
torchvision是Pytorch中专门用来处理图像的库
https://pytorch.org/docs/stable/torchvision/index.html
包中有四大类
torchvision.datasets
torchvision.models
torchvision.transforms
torchvision.utils
###################
torchvision.datasets包含了很多的数据集
torchvision.models包含了一些经典的模型
torchvision.transforms包含了一些图像处理的操作
'''''''''''